[global]
address = "0.0.0.0"
port = 8080
log = "normal"

# [development]
# address = "0.0.0.0"
# port = 4080
# #workers = [number_of_cpus * 2]
# log = "normal"
# #secret_key = [randomly generated at launch]
# #limits = { forms = 32768 }
# 
# [staging]
# address = "0.0.0.0"
# port = 4080
# #workers = [number_of_cpus * 2]
# log = "normal"
# #secret_key = [randomly generated at launch]
# #limits = { forms = 32768 }
# 
# [production]
# address = "0.0.0.0"
# port = 80
# #workers = [number_of_cpus * 2]
# log = "normal"
# #secret_key = [randomly generated at launch]
# #limits = { forms = 32768 }