name: Rust

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**.md"
  # pull_request:
  #   branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose

    # Upload & Release
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: actions-pg
        path: target/release/actions-pg
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actionsdownload-artifact@master
        with:
          name: actions-pg
          path: staging

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Copy files to S3 with the AWS CLI
      run: |
        aws s3 sync staging s3://blackdex-github-actions

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy/@v1
      with:
        name: GitubActions
        template: ec2instance_linux_master_template.yaml
        capabilities: CAPABILITY_NAMED_IAM
