name: Rust

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**.md"
  # pull_request:
  #   branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose

    # Upload & Release
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: actions-pg
        path: target/release/actions-pg
